
---

### 📄 `fly.toml`

```toml
# fly.toml

app = "agentlayer-backend"
primary_region = "nrt"

[build]
  dockerfile = "Dockerfile"

[env]
  PORT = "8000"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
